### ISSUE TITLE
Memory error when training sdxl slider

### ISSUE THREAD

**Issue by RoyDingZF** [ostris/ai-toolkit#10]
Traceback (most recent call last):
  File "D:\01_AItools\ai-toolkit\run.py", line 75, in <module>
    main()
  File "D:\01_AItools\ai-toolkit\run.py", line 71, in main
    raise e
  File "D:\01_AItools\ai-toolkit\run.py", line 62, in main
    job = get_job(config_file, args.name)
  File "D:\01_AItools\ai-toolkit\toolkit\job.py", line 20, in get_job
    return TrainJob(config)
  File "D:\01_AItools\ai-toolkit\jobs\TrainJob.py", line 40, in __init__
    self.load_processes(process_dict)
  File "D:\01_AItools\ai-toolkit\jobs\BaseJob.py", line 65, in load_processes
    self.process.append(ProcessClass(i, self, process))
  File "D:\01_AItools\ai-toolkit\jobs\process\TrainSliderProcess.py", line 32, in __init__
    self.slider_config = SliderConfig(**self.get_conf('slider', {}))
  File "D:\01_AItools\ai-toolkit\toolkit\config_modules.py", line 154, in __init__
    target_permutations = get_slider_target_permutations(target)
  File "D:\01_AItools\ai-toolkit\toolkit\prompt_utils.py", line 255, in get_slider_target_permutations
    neg_permutations = get_permutations(target.negative)
  File "D:\01_AItools\ai-toolkit\toolkit\prompt_utils.py", line 246, in get_permutations
    permutations = list(itertools.permutations(phrases))
MemoryError

**Comment by RoyDingZF** [comment]
1 got 16g RAM, when the script running it consumes almost 100%. Is this script demands more RAM? weird cause I tried it the first time it worked.

**Comment by jaretburkett** [comment]
The permutations error should have been fixed. If you wouldn't mind, can you pull and try again? There are also a lot of memory optimizations on the development branch. I have not merged it to main for a release in a while. You may have better luck on that branch as well. Closing for now. Reopen if you still have issues.
