### ISSUE TITLE
Error running job: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by OutsideDimension2** [ostris/ai-toolkit#100]
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\fluxtraining\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\fluxtraining\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\fluxtraining\ai-toolkit\run.py", line 78, in main
    job.run()
  File "C:\fluxtraining\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "C:\fluxtraining\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1230, in run
    self.sd.load_model()
  File "C:\fluxtraining\ai-toolkit\toolkit\stable_diffusion_model.py", line 487, in load_model
    transformer = FluxTransformer2DModel.from_pretrained(
  File "C:\fluxtraining\ai-toolkit\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\fluxtraining\ai-toolkit\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "C:\fluxtraining\ai-toolkit\venv\lib\site-packages\accelerate\big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "C:\fluxtraining\ai-toolkit\venv\lib\site-packages\accelerate\utils\modeling.py", line 1758, in load_checkpoint_in_model
    loaded_checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
  File "C:\fluxtraining\ai-toolkit\venv\lib\site-packages\accelerate\utils\modeling.py", line 1452, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

i'm getting this error

**Comment by martintomov** [comment]
you should use this script by comfyanonymous to convert the lora for it to work in comfy:
https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/blob/main/convert.py

**Comment by jaretburkett** [comment]
It appears you are not using the default model file. Please use the huggingface repo name in the example configs
