### ISSUE TITLE
Stuck at this point 

### ISSUE THREAD

**Issue by CodeAlexx** [ostris/ai-toolkit#110]
Did you already ask [in the discord](https://discord.com/invite/nuR9zZ2nsh)?
Yes, I was simply ignored 
Yes/No

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.com/invite/nuR9zZ2nsh)?
Tried 2 times 
Yes/No

## Describe the bug

I have Cuda installed and my other programs run and use it, yet I get this error 
git cloned flux dev and now another issue unning  1 process
Loading Flux model
Loading transformer
Error running job: Torch not compiled with CUDA enabled

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "E:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "E:\ai-toolkit\run.py", line 86, in main
    raise e
  File "E:\ai-toolkit\run.py", line 78, in main
    job.run()
  File "E:\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "E:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1230, in run
    self.sd.load_model()
  File "E:\ai-toolkit\toolkit\stable_diffusion_model.py", line 493, in load_model
    transformer.to(torch.device(self.quantize_device), dtype=dtype)
  File "C:\Users\Alexn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "C:\Users\Alexn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\Alexn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\Alexn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\Alexn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "C:\Users\Alexn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
  File "C:\Users\Alexn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

How do I enable Cuda with torch ?

**Comment by CodeAlexx** [comment]
I did not see one opened already from my phone on thus.
