### ISSUE TITLE
Slider Torch error: "optimizer got an empty parameter list"

### ISSUE THREAD

**Issue by gui-nvieira** [ostris/ai-toolkit#15]
The "optimizer got an empty parameter list" problem is persisting when I try to train sliders, no matter how much I change the yml. I did a clean install of this repository to try to solve it and it didn't work. I'm on Windows 11 pro w/ Python 3.10.9

```
Traceback (most recent call last):
  File "[...]\ai-toolkit\run.py", line 75, in <module>
    main()
  File "[...]\ai-toolkit\run.py", line 71, in main
    raise e
  File "[...]\ai-toolkit\run.py", line 63, in main
    job.run()
  File "[...]\ai-toolkit\jobs\TrainJob.py", line 49, in run
    process.run()
  File "[...]\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 484, in run
    optimizer = get_optimizer(params, optimizer_type, learning_rate=self.train_config.lr,
  File "[...]\ai-toolkit\toolkit\optimizer.py", line 53, in get_optimizer
    optimizer = torch.optim.AdamW(params, lr=float(learning_rate), **optimizer_params)
  File "[...]\ai-toolkit\venv\lib\site-packages\torch\optim\adamw.py", line 50, in __init__
    super().__init__(params, defaults)
  File "[...]\ai-toolkit\venv\lib\site-packages\torch\optim\optimizer.py", line 187, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```

Also, thank you very much for your work :)

**Comment by FiveLayersOfCorrugatedCardboard** [comment]
I ran into the same problem, and what got me past that was force installing diffusers version 0.20.0.

**Comment by gui-nvieira** [comment]
> I ran into the same problem, and what got me past that was force installing diffusers version 0.20.0.

Thank dude!

**Comment by andreykhromov** [comment]
>installing diffusers version 0.20.0.

I tried this approach, but all I get is 

`RuntimeError: cutlassF: no kernel found to launch!`

I tried this with every GPU on colab using several branches of this repository, including development and sdxl, on several commits including bee0b6a2358b71445c2922224b1a031ca929394302, but alas. I also tried a PC with a Quadro RTX 8000 with the same result.

The error on the colab as follows:

```
{
    "type": "slider",
    "network": {
        "type": "lora",
        "linear": 8,
        "linear_alpha": 4
    },
    "train": {
        "noise_scheduler": "ddpm",
        "steps": 500,
        "lr": 0.0002,
        "gradient_checkpointing": true,
        "train_unet": true,
        "train_text_encoder": false,
        "optimizer": "adamw",
        "lr_scheduler": "constant",
        "max_denoising_steps": 40,
        "batch_size": 1,
        "dtype": "bf16",
        "noise_offset": 0.0
    },
    "model": {
        "name_or_path": "/content/sd_xl_base_1.0.safetensors",
        "is_v2": false,
        "is_v_pred": false,
        "is_xl": true
    },
    "save": {
        "dtype": "float16",
        "save_every": 50,
        "max_step_saves_to_keep": 2
    },
    "sample": {
        "sampler": "ddpm",
        "sample_every": 20,
        "width": 1024,
        "height": 1024,
        "prompts": [
            "person in blue clothes waiting under a stormy sky, lightning in the distance, --m -10",
            "person in red clothes enjoying a barbecue on a sunny day, kids playing in the yard, --m 10",
            "person in blue clothes stuck in a traffic jam, honking cars, overcast weather, --m -10",
            "person in red clothes at a street festival, live music, sunny afternoon, --m 10",
            "person in blue clothes in a quiet library, whispering, soft rain against the windows, --m -10",
            "person in red clothes at a book club, lively discussion, warm indoor lighting, --m 10",
            "person in blue clothes at a delayed train station, cold and impersonal, --m -10",
            "person in red clothes boarding a luxury cruise, excitement, and waves lapping the hull, --m 10",
            "person in blue clothes in a dimly lit office, working late, the glow of computer screens, --m -10",
            "person in red clothes in a bustling open-plan office, collaboration, bright morning light, --m 10",
            "person in blue clothes walking through a withered garden, bare branches, overcast morning, --m -10",
            "person in red clothes in a vibrant garden party, laughter, sunny and bright, --m 10",
            "person in blue clothes observing a fading mural, quiet contemplation, cloudy dusk, --m -10",
            "person in red clothes painting a colorful street mural, creativity, afternoon sun, --m 10",
            "person in blue clothes at a somber vigil, candlelight, night-time silence, --m -10",
            "person in red clothes at a festive parade, confetti, clear blue skies, --m 10",
            "person in blue clothes in a deserted playground, swings creaking, grey dawn, --m -10",
            "person in red clothes at a lively playground, children's laughter, sunny midday, --m 10",
            "person in blue clothes in an empty caf\u00e9, silent baristas, overcast noon, --m -10",
            "person in red clothes in a cozy caf\u00e9, the sound of a steaming espresso machine, morning light, --m 10",
            "person in blue clothes at a dim subway station, flickering lights, --m -10",
            "person in red clothes at a rooftop party, city skyline, sunset, --m 10",
            "person in blue clothes in an overcrowded elevator, tense silence, --m -10",
            "person in red clothes on a scenic mountain hike, panoramic views, --m 10",
            "person in blue clothes at a silent auction, stark white walls, --m -10",
            "person in red clothes at a carnival, vibrant rides, cheerful music, --m 10",
            "person in blue clothes in a cold hospital waiting room, flickering TV, --m -10",
            "person in red clothes at a cozy mountain lodge, crackling fireplace, --m 10",
            "person in blue clothes at a rainy funeral, umbrellas in a row, --m -10",
            "person in red clothes at a sunny graduation ceremony, throwing caps, --m 10",
            "person in blue clothes in a lost luggage office, frustration, --m -10",
            "person in red clothes at an airport greeting loved ones, joyful reunions, --m 10",
            "person in blue clothes in a stranded ski lift, cold wind, --m -10",
            "person in red clothes at a ski resort's warm lodge, hot cocoa, --m 10",
            "person in blue clothes in an office during a power outage, stillness, --m -10",
            "person in red clothes at a company team-building retreat, laughter, --m 10",
            "person in blue clothes in a quiet, empty art gallery, echo footsteps, --m -10",
            "person in red clothes at an art class, vibrant paints, --m 10",
            "person in blue clothes on a sinking boat, stormy sea, --m -10",
            "person in red clothes on a luxury yacht, calm sea, --m 10",
            "person in blue clothes in a closed amusement park, silent rides, --m -10",
            "person in red clothes at a live concert in the park, energetic crowd, --m 10",
            "person in blue clothes in a desolate parking lot, abandoned carts, --m -10",
            "person in red clothes at a bustling farmers' market, fresh produce, --m 10",
            "person in blue clothes in a dark photography darkroom, solitude, --m -10",
            "person in red clothes at a vibrant street art exhibition, interactive installations, --m 10"
        ],
        "neg": "text, watermark, low-quality, signature, moir\u00e9 pattern, downsampling, aliasing, distorted, blurry, glossy, blur, jpeg artifacts, compression artifacts, poorly drawn, low-resolution, bad, distortion, twisted, excessive, exaggerated pose, exaggerated limbs, grainy, symmetrical, duplicate, error, pattern, beginner, pixelated, fake, hyper, glitch, overexposed, high-contrast, bad-contrast",
        "seed": 42,
        "walk_seed": false,
        "guidance_scale": 7,
        "sample_steps": 30,
        "network_multiplier": 1.0
    },
    "logging": {
        "log_every": 10,
        "use_wandb": false,
        "verbose": false
    },
    "slider": {
        "resolutions": [
            [
                1024,
                1024
            ]
        ],
        "batch_full_slide": true,
        "targets": [
            {
                "target_class": "clothes",
                "positive": "red clothes",
                "negative": "blue clothes",
                "weight": 1.0
            }
        ]
    }
}

#############################################
# Running job: test_slider_v1
#############################################


Running  1 process
create LoRA network. base dim (rank): 8, alpha: 4
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder: 0 modules.
create LoRA for U-Net: 560 modules.
enable LoRA for U-Net
Prompt tensors not found. Encoding prompts..
Generating baseline samples before training
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-8519949f2c4c> in <cell line: 1>()
----> 1 run_job(job_to_run)

22 frames
/content/ai-toolkit/toolkit/job.py in run_job(config, name)
     41 ):
     42     job = get_job(config, name)
---> 43     job.run()
     44     job.cleanup()

/content/ai-toolkit/jobs/TrainJob.py in run(self)
     47 
     48         for process in self.process:
---> 49             process.run()

/content/ai-toolkit/jobs/process/BaseSDTrainProcess.py in run(self)
    507         else:
    508             self.print("Generating baseline samples before training")
--> 509             self.sample(0)
    510 
    511         self.progress_bar = tqdm(

/content/ai-toolkit/jobs/process/BaseSDTrainProcess.py in sample(self, step, is_first)
    146 
    147         # send to be generated
--> 148         self.sd.generate_images(gen_img_config_list)
    149 
    150     def update_training_metadata(self):

/content/ai-toolkit/toolkit/stable_diffusion_model.py in generate_images(self, image_configs)
    345                             grs = 0.7
    346 
--> 347                         img = pipeline(
    348                             prompt=gen_config.prompt,
    349                             prompt_2=gen_config.prompt_2,

/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py in __call__(self, prompt, prompt_2, height, width, num_inference_steps, denoising_end, guidance_scale, negative_prompt, negative_prompt_2, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, output_type, return_dict, callback, callback_steps, cross_attention_kwargs, guidance_rescale, original_size, crops_coords_top_left, target_size)
    810                 # predict the noise residual
    811                 added_cond_kwargs = {"text_embeds": add_text_embeds, "time_ids": add_time_ids}
--> 812                 noise_pred = self.unet(
    813                     latent_model_input,
    814                     t,

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py in forward(self, sample, timestep, encoder_hidden_states, class_labels, timestep_cond, attention_mask, cross_attention_kwargs, added_cond_kwargs, down_block_additional_residuals, mid_block_additional_residual, encoder_attention_mask, return_dict)
    928                     additional_residuals["additional_residuals"] = down_block_additional_residuals.pop(0)
    929 
--> 930                 sample, res_samples = downsample_block(
    931                     hidden_states=sample,
    932                     temb=emb,

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py in forward(self, hidden_states, temb, encoder_hidden_states, attention_mask, cross_attention_kwargs, encoder_attention_mask, additional_residuals)
   1051             else:
   1052                 hidden_states = resnet(hidden_states, temb)
-> 1053                 hidden_states = attn(
   1054                     hidden_states,
   1055                     encoder_hidden_states=encoder_hidden_states,

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

/usr/local/lib/python3.10/dist-packages/diffusers/models/transformer_2d.py in forward(self, hidden_states, encoder_hidden_states, timestep, class_labels, cross_attention_kwargs, attention_mask, encoder_attention_mask, return_dict)
    307                 )
    308             else:
--> 309                 hidden_states = block(
    310                     hidden_states,
    311                     attention_mask=attention_mask,

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

/usr/local/lib/python3.10/dist-packages/diffusers/models/attention.py in forward(self, hidden_states, attention_mask, encoder_hidden_states, encoder_attention_mask, timestep, cross_attention_kwargs, class_labels)
    192         gligen_kwargs = cross_attention_kwargs.pop("gligen", None)
    193 
--> 194         attn_output = self.attn1(
    195             norm_hidden_states,
    196             encoder_hidden_states=encoder_hidden_states if self.only_cross_attention else None,

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py in forward(self, hidden_states, encoder_hidden_states, attention_mask, **cross_attention_kwargs)
    320         # here we simply pass along all tensors to the selected processor class
    321         # For standard processors that are defined here, `**cross_attention_kwargs` is empty
--> 322         return self.processor(
    323             self,
    324             hidden_states,

/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py in __call__(self, attn, hidden_states, encoder_hidden_states, attention_mask, temb)
   1115         # the output of sdp = (batch, num_heads, seq_len, head_dim)
   1116         # TODO: add support for attn.scale when we move to Torch 2.1
-> 1117         hidden_states = F.scaled_dot_product_attention(
   1118             query, key, value, attn_mask=attention_mask, dropout_p=0.0, is_causal=False
   1119         )

RuntimeError: cutlassF: no kernel found to launch!
```
