### ISSUE TITLE
Run.py Issue 

### ISSUE THREAD

**Issue by QuietSkulls** [ostris/ai-toolkit#178]
I don't have Discord, but this is my issue I keep running into: 

Traceback (most recent call last):
  File "/workspace/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/workspace/ai-toolkit/run.py", line 86, in main
    raise e
  File "/workspace/ai-toolkit/run.py", line 78, in main
    job.run()
  File "/workspace/ai-toolkit/jobs/ExtensionJob.py", line 22, in run
    process.run()
  File "/workspace/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 1567, in run
    self.data_loader = get_dataloader_from_datasets(self.datasets, self.train_config.batch_size, self.sd)
  File "/workspace/ai-toolkit/toolkit/data_loader.py", line 571, in get_dataloader_from_datasets
    dataset = AiToolkitDataset(config, batch_size=batch_size, sd=sd)
  File "/workspace/ai-toolkit/toolkit/data_loader.py", line 411, in __init__
    with open(self.dataset_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/ai-toolkit/Dataset'
![image](https://github.com/user-attachments/assets/81ea0210-4a45-4ded-be88-84760491619c)

**Comment by QuietSkulls** [comment]
Nevermind, I figured it out. I didn't put an "/ " in front of the beginning of the path.
