### ISSUE TITLE
Error running job: cannot import name 'packaging' from 'pkg_resources'

### ISSUE THREAD

**Issue by VictorLab75** [ostris/ai-toolkit#187]
Hello, after reinstalling ai-toolkit, I can't seem to run my Lora training

```
(venv) PS C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit> python run.py config/my_lora_01.yaml
Running 1 job
C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\venv\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.17 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
Error running job: cannot import name 'packaging' from 'pkg_resources' (C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\venv\Lib\site-packages\pkg_resources\__init__.py)

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\run.py", line 77, in main
    job = get_job(config_file, args.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\toolkit\job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\jobs\process\__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\jobs\process\TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 42, in <module>
    from toolkit.sampler import get_sampler
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\toolkit\sampler.py", line 22, in <module>
    from k_diffusion.external import CompVisDenoiser
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\venv\Lib\site-packages\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\venv\Lib\site-packages\k_diffusion\evaluation.py", line 6, in <module>
    import clip
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\venv\Lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\venv\Lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit\venv\Lib\site-packages\pkg_resources\__init__.py)
(venv) PS C:\Users\User\Desktop\Tools\Stable Diffusion\ai-toolkit>
```

**Comment by chadjuby** [comment]
I'm getting the same issue, I haven't found a resolution yet.

**Comment by chadjuby** [comment]
I just resolved it by reverting to an earlier version of setuptools:
pip install setuptools==69.5.1

**Comment by De-Zoomer** [comment]
> pip install setuptools==69.5.1

Thanks @chadjuby, this command fixed a fresh install on Windows. Perhaps it should be updated in the original requirements.txt here in the repo.
