### ISSUE TITLE
Error running ai-toolkit on runpod.io checkout 03-10-24

### ISSUE THREAD

**Issue by jalberty2018** [ostris/ai-toolkit#188]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)?

No

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

## Describe the bug

Following error when running ai-toolkit from git pull 03-10-24 on runpod.io
My image created on 23-09-24 works perfect (tag 40a8ff57311d2545b5fbd0226988acda3015d6cf). 
Creating an image today from git checkout 23-09-24 gives the same error.
Installing it manually on a base image gives the same error
Running pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime as base in both images.
Same problem with or without venv.

## Output

(venv) root@98fbad8a6724:/workspace/ai-toolkit# python3 run.py /workspace/test/config.yaml
Running 1 job
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
/workspace/ai-toolkit/venv/lib/python3.11/site-packages/albumentations/__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.17 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
/workspace/ai-toolkit/venv/lib/python3.11/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
/workspace/ai-toolkit/venv/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/workspace/ai-toolkit/venv/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/workspace/ai-toolkit/venv/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/workspace/ai-toolkit/venv/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/workspace/ai-toolkit/venv/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)

.
.
.

Running  1 process
Loading Flux model
Loading transformer
transformer/config.json: 100%|████████████████████████████████████████████| 421/421 [00:00<00:00, 1.82MB/s]
(…)ion_pytorch_model.safetensors.index.json: 100%|██████████████████████| 121k/121k [00:00<00:00, 76.3MB/s]
(…)pytorch_model-00001-of-00003.safetensors: 100%|████████████████████▉| 9.98G/9.98G [00:13<00:00, 751MB/s]
(…)pytorch_model-00002-of-00003.safetensors: 100%|████████████████████▉| 9.95G/9.95G [00:12<00:00, 775MB/s]
(…)pytorch_model-00003-of-00003.safetensors: 100%|████████████████████▉| 3.87G/3.87G [00:05<00:00, 674MB/s]
Quantizing transformer
Error running job: Command '['which', 'c++']' returned non-zero exit status 1.

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "/workspace/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/workspace/ai-toolkit/run.py", line 86, in main
    raise e
  File "/workspace/ai-toolkit/run.py", line 78, in main
    job.run()
  File "/workspace/ai-toolkit/jobs/ExtensionJob.py", line 22, in run
    process.run()
  File "/workspace/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 1241, in run
    self.sd.load_model()
  File "/workspace/ai-toolkit/toolkit/stable_diffusion_model.py", line 599, in load_model
    freeze(transformer)
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/quantize.py", line 146, in freeze
    m.freeze()
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/nn/qmodule.py", line 299, in freeze
    qweight = self.qweight
              ^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/nn/qmodule.py", line 265, in qweight
    return quantize_weight(
           ^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/tensor/weights/quantization.py", line 70, in quantize_weight
    return WeightQBytesTensor.quantize(t, qtype, axis, scale, activation_qtype, optimized)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/tensor/weights/qbytes.py", line 165, in quantize
    return WeightQBytesQuantizer.apply(base, qtype, axis, scale, activation_qtype, optimized)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/tensor/weights/qbytes.py", line 43, in forward
    return WeightQBytesTensor.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/tensor/weights/qbytes.py", line 140, in create
    return MarlinF8QBytesTensor(qtype, axis, size, stride, data, scale, requires_grad)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/tensor/weights/marlin/fp8/qbits.py", line 80, in __init__
    data_packed = MarlinF8PackedTensor.pack(data)  # pack fp8 data to in32, and apply marlier re-ordering.
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/tensor/weights/marlin/fp8/packed.py", line 183, in pack
    data_int32 = torch.ops.quanto.pack_fp8_marlin(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/torch/_ops.py", line 1061, in __call__
    return self_._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/library/extensions/cuda/__init__.py", line 164, in gptq_marlin_repack
    return ext.lib.gptq_marlin_repack(b_q_weight, perm, size_k, size_n, num_bits)
           ^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/optimum/quanto/library/extensions/extension.py", line 42, in lib
    self._lib = load(
                ^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1808, in _write_ninja_file_and_build_library
    get_compiler_abi_compatibility_and_version(compiler)
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 358, in get_compiler_abi_compatibility_and_version
    if not check_compiler_ok_for_platform(compiler):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ai-toolkit/venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 311, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
(venv) root@98fbad8a6724:/workspace/ai-toolkit#

**Comment by jalberty2018** [comment]
Will check first if i have a compiler installed as i am using a runtime image instead of a development one
Chatgpt help for this ... 8-)

"The error message you're seeing indicates that the command which c++ was executed and returned a non-zero exit status, meaning that the command did not successfully find the c++ compiler on your system."

**Comment by jalberty2018** [comment]
Solved my own problem... so proud.
Changed the base version to: 
FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel AS base
Installed:
apt-get update build-essential make cmake
