### ISSUE TITLE
AttributeError: module 'timm.models._registry' has no attribute 'get_pretrained_cfgs_for_arch'. Did you mean: 'get_pretrained_cfg_value'?

### ISSUE THREAD

**Issue by TrickyBarrel** [ostris/ai-toolkit#197]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)?

No

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

## Describe the bug

AttributeError: module 'timm.models._registry' has no attribute 'get_pretrained_cfgs_for_arch'. Did you mean: 'get_pretrained_cfg_value'?

New timm package version is responsible for this error, downgrading to timm 1.0.9 fixes the issue.

**Comment by EnragedAntelope** [comment]
Thank you! I have same issue:
```

Creating dataset
Started training
Traceback (most recent call last):
  File "C:\ai-toolkit\venv\Lib\site-packages\gradio\queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\venv\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\venv\Lib\site-packages\gradio\blocks.py", line 2014, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\venv\Lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\ai-toolkit\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\venv\Lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\flux_train_ui.py", line 229, in start_training
    job = get_job(config_path)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\toolkit\job.py", line 29, in get_job
    return ExtensionJob(config)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\jobs\ExtensionJob.py", line 12, in __init__
    self.process_dict = get_all_extensions_process_dict()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\toolkit\extension.py", line 56, in get_all_extensions_process_dict
    process_dict[extension.uid] = extension.get_process()
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\extensions_built_in\advanced_generator\__init__.py", line 18, in get_process
    from .ReferenceGenerator import ReferenceGenerator
  File "C:\ai-toolkit\extensions_built_in\advanced_generator\ReferenceGenerator.py", line 22, in <module>
    from controlnet_aux.midas import MidasDetector
  File "C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\__init__.py", line 16, in <module>
    from .segment_anything import SamDetector
  File "C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\__init__.py", line 18, in <module>
    from .automatic_mask_generator import SamAutomaticMaskGenerator
  File "C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\automatic_mask_generator.py", line 13, in <module>
    from .modeling import Sam
  File "C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\__init__.py", line 7, in <module>
    from .sam import Sam
  File "C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\sam.py", line 13, in <module>
    from .tiny_vit_sam import TinyViT
  File "C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py", line 17, in <module>
    from timm.models.registry import register_model
  File "C:\ai-toolkit\venv\Lib\site-packages\timm\models\registry.py", line 1, in <module>
    from ._registry import *
AttributeError: module 'timm.models._registry' has no attribute 'get_pretrained_cfgs_for_arch'

```

**Comment by pauliustumas** [comment]
`pip install 'timm==1.0.9'`

helped for me
