### ISSUE TITLE
RuntimeError: CUTLASS submodule not found.

### ISSUE THREAD

**Issue by Azazellz** [ostris/ai-toolkit#20]
I'm a newbie, and wanted to try to train the Slider-Lora. 
However, when installing according to your instructions, the console keeps showing me this:

```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Azazellz\AppData\Local\Temp\pip-install-odh8ca7q\xformers_6ea7f7dc889b49b9891defb237c7fa97\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\Azazellz\AppData\Local\Temp\pip-install-odh8ca7q\xformers_6ea7f7dc889b49b9891defb237c7fa97\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]
```
I've tried doing `git submodule update --init --recursive` as it said - nothing.
Tried even cloning CUTLASS manually into the repositories folder (don't know if that was supposed to help) - nothing.

Google Сolab produces something related to Cutlass too:
![17016066241680](https://github.com/ostris/ai-toolkit/assets/123301197/ab317916-7e71-4f1a-a56a-9eb95579d1b3)

**Comment by PotatoBananaApple** [comment]
Tried clean install, got same error on windows.
