### ISSUE TITLE
error when training sd3.5: has no attribute norm_added_k

### ISSUE THREAD

**Issue by JoshonSmith** [ostris/ai-toolkit#201]
the error msg is blow:

```
#############################################
# Running job: boy_sd3l_lora_v1
#############################################


Running  1 process
Loading SD3 model
Loading transformer

Error running job: Attention(
  (to_q): Linear(in_features=2432, out_features=2432, bias=True)
  (to_k): Linear(in_features=2432, out_features=2432, bias=True)
  (to_v): Linear(in_features=2432, out_features=2432, bias=True)
  (add_k_proj): Linear(in_features=2432, out_features=2432, bias=True)
  (add_v_proj): Linear(in_features=2432, out_features=2432, bias=True)
  (add_q_proj): Linear(in_features=2432, out_features=2432, bias=True)
  (to_out): ModuleList(
    (0): Linear(in_features=2432, out_features=2432, bias=True)
    (1): Dropout(p=0.0, inplace=False)
  )
  (to_add_out): Linear(in_features=2432, out_features=2432, bias=True)
) has no attribute norm_added_k.

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "ai-toolkit-sd35/run.py", line 90, in <module>
    main()
  File "ai-toolkit-sd35/run.py", line 86, in main
    raise e
  File "ai-toolkit-sd35/run.py", line 78, in main
    job.run()
  File "ai-toolkit-sd35/jobs/ExtensionJob.py", line 22, in run
    process.run()
  File "ai-toolkit-sd35/jobs/process/BaseSDTrainProcess.py", line 1242, in run
    self.sd.load_model()
  File "ai-toolkit-sd35/toolkit/stable_diffusion_model.py", line 291, in load_model
    transformer = SD3Transformer2DModel.from_pretrained(
  File "python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "python3.10/site-packages/diffusers/models/modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "python3.10/site-packages/accelerate/big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "python3.10/site-packages/accelerate/utils/modeling.py", line 1821, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "python3.10/site-packages/accelerate/utils/modeling.py", line 336, in set_module_tensor_to_device
    raise ValueError(f"{module} has no attribute {split}.")
ValueError: Attention(
  (to_q): Linear(in_features=2432, out_features=2432, bias=True)
  (to_k): Linear(in_features=2432, out_features=2432, bias=True)
  (to_v): Linear(in_features=2432, out_features=2432, bias=True)
  (add_k_proj): Linear(in_features=2432, out_features=2432, bias=True)
  (add_v_proj): Linear(in_features=2432, out_features=2432, bias=True)
  (add_q_proj): Linear(in_features=2432, out_features=2432, bias=True)
  (to_out): ModuleList(
    (0): Linear(in_features=2432, out_features=2432, bias=True)
    (1): Dropout(p=0.0, inplace=False)
  )
  (to_add_out): Linear(in_features=2432, out_features=2432, bias=True)
) has no attribute norm_added_k.

```

**Comment by NBSTpeterhill** [comment]
Update your vene folder, mainly to ensure that the diffusers component is up to date.

**Comment by bparrott78** [comment]
> Update your vene folder, mainly to ensure that the diffusers component is up to date.

venv folder?

**Comment by jsemrau** [comment]
I think what NBSTpeterhill means is something like 

pip install --upgrade -r requirements.txt

**Comment by JoshonSmith** [comment]
> Update your vene folder, mainly to ensure that the diffusers component is up to date.

it works！
update diffusers
thanks
