### ISSUE TITLE
OSError: black-forest-labs/FLUX.1-dev does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by Amon1412** [ostris/ai-toolkit#209]
Traceback (most recent call last):
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd2b1689990>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /black-forest-labs/FLUX.1-dev/resolve/main/transformer/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd2b1689990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /black-forest-labs/FLUX.1-dev/resolve/main/transformer/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd2b1689990>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 8b49e1ce-3d54-42ea-b148-1326ddef2ca1)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/mnt/workspace/ai-toolkit/run.py", line 86, in main
    raise e
  File "/mnt/workspace/ai-toolkit/run.py", line 78, in main
    job.run()
  File "/mnt/workspace/ai-toolkit/jobs/ExtensionJob.py", line 22, in run
    process.run()
  File "/mnt/workspace/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 1258, in run
    self.sd.load_model()
  File "/mnt/workspace/ai-toolkit/toolkit/stable_diffusion_model.py", line 546, in load_model
    transformer = FluxTransformer2DModel.from_pretrained(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 640, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/workspace/ai-toolkit/venv/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 406, in load_config
    raise EnvironmentError(
OSError: black-forest-labs/FLUX.1-dev does not appear to have a file named config.json.

**Comment by Amon1412** [comment]
I solved the problem by setting up a proxy
