### ISSUE TITLE
Slider training not working

### ISSUE THREAD

**Issue by Volnovik** [ostris/ai-toolkit#227]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

## Describe the bug

Slider training gives following 

`Traceback (most recent call last):
  File "S:\Train\Ostris\ai-toolkit\run.py", line 90, in <module>
    main()
  File "S:\Train\Ostris\ai-toolkit\run.py", line 86, in main
    raise e
  File "S:\Train\Ostris\ai-toolkit\run.py", line 78, in main
    job.run()
  File "S:\Train\Ostris\ai-toolkit\jobs\TrainJob.py", line 49, in run
    process.run()
  File "S:\Train\Ostris\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1776, in run
    loss_dict = self.hook_train_loop(batch_list)
  File "S:\Train\Ostris\ai-toolkit\jobs\process\TrainSliderProcess.py", line 338, in hook_train_loop
    noisy_latents, noise, timesteps, conditioned_prompts, imgs = self.process_general_training_batch(batch)
  File "S:\Train\Ostris\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 786, in process_general_training_batch
    prompts = batch.get_caption_list()
AttributeError: 'list' object has no attribute 'get_caption_list'`

Tried both custom and example, same result. Switching to different branches also does not help.

**Comment by CBLee1978** [comment]
This bug still exists as of 7/28/2026. Slider LoRA training is still impossible due to this error.

LECO sliders naturally do not use captions, training images, regularization, etc., however, it seems that there is code in place that integrates captions, regularization, etc. into slider training workflow.

There are LECO training alternatives, but none of them worked as well as, or are as mature as AI-Toolkit's implementation. I hope this gets fixed at some point.

**Comment by Heetoprime** [comment]
> This bug still exists as of 7/28/2026. Slider LoRA training is still impossible due to this error.
> 
> LECO sliders naturally do not use captions, training images, regularization, etc., however, it seems that there is code in place that integrates captions, regularization, etc. into slider training workflow.
> 
> There are LECO training alternatives, but none of them worked as well as, or are as mature as AI-Toolkit's implementation. I hope this gets fixed at some point.

Your fix worked for me! Thank you! Would like to see this fixed too.

**Comment by CBLee1978** [comment]
> Your fix worked for me! Thank you! Would like to see this fixed too.

What fix? The slider trainer still appears to be broken.

**Comment by Heetoprime** [comment]
Oh I meant your batch[0] code fixed a separate issue, but the slider trainer is still broken. Didn't mean to mislead.

**Comment by Volnovik** [comment]
It works, you just need to provide it a captioned dataset. Why? Because implementation. Take a look at Ostris's video on YouTube. 
Unfortunately this whole thing is not documented at all.

**Comment by Heetoprime** [comment]
> It works, you just need to provide it a captioned dataset. Why? Because implementation. Take a look at Ostris's video on YouTube. Unfortunately this whole thing is not documented at all.

It works! I had to give the concept slider job a captioned dataset, and then it worked. I would've preferred to just give it text prompts but it works, just finicky. Thanks for the tip.
I also had to update optimum-quanto to work with Anima.

**Comment by CBLee1978** [comment]
> It works! I had to give the concept slider job a captioned dataset, and then it worked. I would've preferred to just give it text prompts but it works, just finicky. Thanks for the tip. I also had to update optimum-quanto to work with Anima.

The dataset doesn't need to be captioned necessarily. Only a few images (6-8) containing your target class is all that's needed. In fact, I don't believe the dataset is used at all for slider training. It only seems to be needed because of how the code is structured.
