### ISSUE TITLE
ModuleNotFoundError: No module named 'networks.lora'，but I can't install this pkg

### ISSUE THREAD

**Issue by github-water** [ostris/ai-toolkit#229]
lora_special.py", line 20, in <module>
    from networks.lora import LoRANetwork, get_block_index
ModuleNotFoundError: No module named 'networks.lora'

**Comment by timmerscher** [comment]
Did you install all the dependencies as recommended?

**Comment by Xqua** [comment]
did you run this

`git submodule update --init --recursive  `

**Comment by Otnielush** [comment]
> i run this `git submodule update --init --recursive ` but i also had this error i don't create menv because i use the conda

git clone all needed repos into "repositories" directory (batch-annotator, ipadapter, leco, sd-scripts)

**Comment by DarkAlchy** [comment]
I am at this error myself.

(venv) F:\ai-toolkit>git submodule update --init --recursive
Submodule 'repositories/batch_annotator' (https://github.com/ostris/batch-annotator) registered for path 'repositories/batch_annotator'
Submodule 'repositories/ipadapter' (https://github.com/tencent-ailab/IP-Adapter.git) registered for path 'repositories/ipadapter'
Submodule 'repositories/leco' (https://github.com/p1atdev/LECO) registered for path 'repositories/leco'
Submodule 'repositories/sd-scripts' (https://github.com/kohya-ss/sd-scripts.git) registered for path 'repositories/sd-scripts'
Cloning into 'F:/ai-toolkit/repositories/batch_annotator'...
Cloning into 'F:/ai-toolkit/repositories/ipadapter'...
Cloning into 'F:/ai-toolkit/repositories/leco'...
Cloning into 'F:/ai-toolkit/repositories/sd-scripts'...
Submodule path 'repositories/batch_annotator': checked out '420e142f6ad3cc14b3ea0500affc2c6c7e7544bf'
Submodule 'repositories/controlnet' (https://github.com/lllyasviel/ControlNet-v1-1-nightly.git) registered for path 'repositories/batch_annotator/repositories/controlnet'
Cloning into 'F:/ai-toolkit/repositories/batch_annotator/repositories/controlnet'...
Submodule path 'repositories/batch_annotator/repositories/controlnet': checked out 'e2b44154b72965c5e11b1ccee941d550682e4701'
Submodule path 'repositories/ipadapter': checked out '5a18b1f3660acaf8bee8250692d6fb3548a19b14'
Submodule path 'repositories/leco': checked out '9294adf40218e917df4516737afb13f069a6789d'
Submodule path 'repositories/sd-scripts': checked out 'b78c0e2a69e52ce6c79abc6c8c82d1a9cabcf05c'


========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "F:\ai-toolkit\run.py", line 119, in <module>
    main()
  File "F:\ai-toolkit\run.py", line 107, in main
    raise e
  File "F:\ai-toolkit\run.py", line 94, in main
    job = get_job(config_file, args.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ai-toolkit\toolkit\job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "F:\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "F:\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "F:\ai-toolkit\jobs\process\__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "F:\ai-toolkit\jobs\process\TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "F:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 27, in <module>
    from toolkit.custom_adapter import CustomAdapter
  File "F:\ai-toolkit\toolkit\custom_adapter.py", line 13, in <module>
    from toolkit.models.control_lora_adapter import ControlLoraAdapter
  File "F:\ai-toolkit\toolkit\models\control_lora_adapter.py", line 5, in <module>
    from toolkit.lora_special import LoRASpecialNetwork
  File "F:\ai-toolkit\toolkit\lora_special.py", line 21, in <module>
    from networks.lora import LoRANetwork, get_block_index
ModuleNotFoundError: No module named 'networks.lora'
