### ISSUE TITLE
Windows not yet supported for torch.compile

### ISSUE THREAD

**Issue by Haoming02** [ostris/ai-toolkit#28]
I'm trying to train a slider, but I encountered this:

```bash
Error running job: Windows not yet supported for torch.compile

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\run.py", line 89, in <module>
    main()
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\run.py", line 85, in main
    raise e
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\run.py", line 77, in main
    job.run()
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\jobs\TrainJob.py", line 49, in run
    process.run()
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1447, in run
    torch.compile(self.sd.unet, dynamic=True)
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\venv\lib\site-packages\torch\__init__.py", line 1826, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 753, in optimize
    check_if_dynamo_supported()
  File "C:\Users\admin\Documents\GitHub\ai-toolkit\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 702, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile
```

Is there something I need to modify to tell it not to use `torch.compile` ?

**Comment by Haoming02** [comment]
Seems to be training now after I comment out [this line](https://github.com/ostris/ai-toolkit/blob/main/jobs/process/BaseSDTrainProcess.py#L1447) at least

**Comment by iamrohitanshu** [comment]
@Haoming02 What model are you training on?
Also, after commenting out that line, did your lora turn out okay in the end?

**Comment by iamrohitanshu** [comment]
Same, training on SDXL gives almost non-existent results here, even at higher learning rates.
Normal training (with images), SDXL never has this issue. I wonder what's going on!
May be it needs way more training steps or something.
