### ISSUE TITLE
ImportError: cannot import name 'AuraFlowTransformer2DModel' from 'diffusers' and other errors.  Just not usable.

### ISSUE THREAD

**Issue by DarkAlchy** [ostris/ai-toolkit#31]
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "D:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "D:\ai-toolkit\run.py", line 86, in main
    raise e
  File "D:\ai-toolkit\run.py", line 77, in main
    job = get_job(config_file, args.name)
  File "D:\ai-toolkit\toolkit\job.py", line 19, in get_job
    from jobs import TrainJob
  File "D:\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "D:\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "D:\ai-toolkit\jobs\process\__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "D:\ai-toolkit\jobs\process\TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "D:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 29, in <module>
    from toolkit.lora_special import LoRASpecialNetwork
  File "D:\ai-toolkit\toolkit\lora_special.py", line 10, in <module>
    from diffusers import UNet2DConditionModel, PixArtTransformer2DModel, AuraFlowTransformer2DModel
ImportError: cannot import name 'AuraFlowTransformer2DModel' from 'diffusers' (D:\ai-toolkit\venv\lib\site-packages\diffusers\__init__.py)

**Comment by DarkAlchy** [comment]
This WIP does not work as I removed all those Pixart and aura flows and had to fight your includes to it finally starting to be hit with more errors.

![image](https://github.com/user-attachments/assets/f6ac6cec-8d2d-4ff5-bf4c-93a18a3c8614)
