### ISSUE TITLE
ModuleNotFoundError: No module named 'ipadapter.ip_adapter'

### ISSUE THREAD

**Issue by scarbain** [ostris/ai-toolkit#33]
Hi, I'm trying to run the training script for Flux but I keep getting this error : 
Traceback (most recent call last):
  File "/workspace/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/workspace/ai-toolkit/run.py", line 86, in main
    raise e
  File "/workspace/ai-toolkit/run.py", line 77, in main
    job = get_job(config_file, args.name)
  File "/workspace/ai-toolkit/toolkit/job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "/workspace/ai-toolkit/jobs/__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "/workspace/ai-toolkit/jobs/BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "/workspace/ai-toolkit/jobs/process/__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "/workspace/ai-toolkit/jobs/process/TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "/workspace/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 23, in <module>
    from toolkit.custom_adapter import CustomAdapter
  File "/workspace/ai-toolkit/toolkit/custom_adapter.py", line 11, in <module>
    from toolkit.models.ilora import InstantLoRAModule
  File "/workspace/ai-toolkit/toolkit/models/ilora.py", line 12, in <module>
    from ipadapter.ip_adapter.resampler import  Resampler
ModuleNotFoundError: No module named 'ipadapter.ip_adapter'

---
Any idea why ?

**Comment by scarbain** [comment]
My bad, I forgot to "git submodule update --init --recursive".
Closing the issue.
