### ISSUE TITLE
flux lora training inWin OS

### ISSUE THREAD

**Issue by pzc163** [ostris/ai-toolkit#34]
When using Windows to fine-tune the model for flux-dev on a 4090 with a single card and 24G of VRAM, I encountered this error

![image](https://github.com/user-attachments/assets/66c1c6e3-da12-41b4-bb11-0a286c0a2802)

**Comment by Desm0nt** [comment]
Similar error, win10, 3090, python 3.10 via Conda. Rank 8, 786*786 resolution:
```
Caching latents to disk: 100%|███████████████████████████████████████████████████████████| 856/856 [03:23<00:00,  4.21it/s]
'CustomFlowMatchEulerDiscreteScheduler' object has no attribute 'alphas_cumprod'
Failed to add all_snr to noise_scheduler
Generating baseline samples before training
raichiyo_lora_v1:   0%|                                                                           | 0/9000 [00:00<?, ?it/s]Error running job: cannot pickle 'weakref.ReferenceType' object

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "F:\5_Training_tools\ai-toolkit\run.py", line 90, in <module>
    main()
  File "F:\5_Training_tools\ai-toolkit\run.py", line 86, in main
    raise e
  File "F:\5_Training_tools\ai-toolkit\run.py", line 78, in main
    job.run()
  File "F:\5_Training_tools\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "F:\5_Training_tools\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1593, in run
    dataloader_iterator = iter(dataloader)
  File "F:\5_Training_tools\ai-toolkit\venv\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "F:\5_Training_tools\ai-toolkit\venv\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\5_Training_tools\ai-toolkit\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "E:\anaconda3\envs\img\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "E:\anaconda3\envs\img\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\anaconda3\envs\img\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "E:\anaconda3\envs\img\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\anaconda3\envs\img\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\anaconda3\envs\img\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\anaconda3\envs\img\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
raichiyo_lora_v1:   0%|                                                                           | 0/9000 [00:00<?, ?it/s]


```

**Comment by bghira** [comment]
i think it's the spawn method for multiprocessing, which has to be set to 'fork' but if you are on Windows i don't think it has fork. this repo might not work on Windows at all.

```py
# set 'fork' spawn mode
import multiprocessing as mp

mp.set_start_method("fork")
```

**Comment by Estylon** [comment]
I've got an error as well that i'm not managing to solve. 
Windows 11 with RTX4090
```

Caching latents for D:\training\Elisa\originals
 - Saving latents to disk
Caching latents to disk: 100%|█████████████████████████████████████████████████████████████████| 33/33 [00:00<?, ?it/s]
'CustomFlowMatchEulerDiscreteScheduler' object has no attribute 'alphas_cumprod'
Failed to add all_snr to noise_scheduler
Generating baseline samples before training
Generating Images:   0%|                                                                        | 0/10 [00:00<?, ?it/s]D:\ai-toolkit\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:480: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
EC Style:   0%|                                                                               | 0/4000 [00:00<?, ?it/s]Error running job: cannot pickle 'weakref.ReferenceType' object

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "D:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "D:\ai-toolkit\run.py", line 86, in main
    raise e
  File "D:\ai-toolkit\run.py", line 78, in main
    job.run()
  File "D:\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "D:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1593, in run
    dataloader_iterator = iter(dataloader)
  File "D:\ai-toolkit\venv\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "D:\ai-toolkit\venv\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\ai-toolkit\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
EC Style:   0%|                                                                               | 0/4000 [00:00<?, ?it/s]
```

**Comment by Desm0nt** [comment]
It's not a fix for a problem, but - rank 8 1024*1024 works fine in WSL on 3090 even with only 32gb RAM

**Comment by jaretburkett** [comment]
Just pushed a fix for this https://github.com/ostris/ai-toolkit/commit/6d31c6db730a9cba3004eae1a3d7283c663d9295 . Not the best way to handle it, but it works for now.
