### ISSUE TITLE
OSError: black-forest-labs/FLUX.1-dev does not appear to have a file named config.json

### ISSUE THREAD

**Issue by zlikwidart** [ostris/ai-toolkit#36]
I've created my .env file with my huggingface token id and I've already accepted the terms on huggingface for flux dev.  Here's the full error stack:

Running  1 process
Loading Flux model
Loading transformer
Error running job: black-forest-labs/FLUX.1-dev does not appear to have a file named config.json.

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/transformer/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\utils\_errors.py", line 367, in hf_raise_for_status
    raise HfHubHTTPError(message, response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError:  (Request ID: Root=1-66b9ae54-216c29bb298627192c2ba54d;1698bf02-0222-423e-84ae-ede08eac617b)

403 Forbidden: Please enable access to public gated repositories in your fine-grained token settings to view this repository..
Cannot access content at: https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/transformer/config.json.
If you are trying to create or update content, make sure you have a token with the `write` role.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\diffusers\configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1857, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\FluxLoraTraining\ai-toolkit\run.py", line 90, in <module>
    main()
  File "Z:\FluxLoraTraining\ai-toolkit\run.py", line 86, in main
    raise e
  File "Z:\FluxLoraTraining\ai-toolkit\run.py", line 78, in main
    job.run()
  File "Z:\FluxLoraTraining\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "Z:\FluxLoraTraining\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1230, in run
    self.sd.load_model()
  File "Z:\FluxLoraTraining\ai-toolkit\toolkit\stable_diffusion_model.py", line 469, in load_model
    transformer = FluxTransformer2DModel.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 612, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "Z:\FluxLoraTraining\ai-toolkit\venv\Lib\site-packages\diffusers\configuration_utils.py", line 406, in load_config
    raise EnvironmentError(
OSError: black-forest-labs/FLUX.1-dev does not appear to have a file named config.json.

**Comment by zlikwidart** [comment]
Never mind.  I guess  I  had my .env file open somewhere and it didn't like that.

**Comment by 1247862674** [comment]
How to fix this error, I'm getting this error as well
