### ISSUE TITLE
No module named 'library' from library.lpw_stable_diffusion

### ISSUE THREAD

**Issue by gvn-49856357** [ostris/ai-toolkit#5]
I am facing this error through windows and google Colab. I made a fork and I'm organizing a colab for the sliders script (as soon as it's fully functional I will disclose). I like your work very much!

Windows:
```
Running 1 job
Error running job: No module named 'library'

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "...\ai-toolkit\run.py", line 73, in <module>
    main()
  File "...\ai-toolkit\run.py", line 69, in main
    raise e
  File "...\ai-toolkit\run.py", line 60, in main
    job = get_job(config_file, args.name)
  File "...\ai-toolkit\toolkit\job.py", line 14, in get_job
    from jobs import TrainJob
  File "...\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "...\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "...\ai-toolkit\jobs\process\__init__.py", line 1, in <module>
    from .BaseExtractProcess import BaseExtractProcess
  File "...\ai-toolkit\jobs\process\BaseExtractProcess.py", line 7, in <module>
    from toolkit.metadata import get_meta_for_safetensors
  File "...\ai-toolkit\toolkit\metadata.py", line 9, in <module>
    from toolkit.train_tools import addnet_hash_legacy
  File "...\ai-toolkit\toolkit\train_tools.py", line 26, in <module>
    from library.lpw_stable_diffusion import StableDiffusionLongPromptWeightingPipeline
ModuleNotFoundError: No module named 'library'
```

Google Colab:
```
Running 1 job
2023-08-10 09:35:19.203675: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Error running job: No module named 'library'

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "/content/ai-toolkit/run.py", line 73, in <module>
    main()
  File "/content/ai-toolkit/run.py", line 69, in main
    raise e
  File "/content/ai-toolkit/run.py", line 60, in main
    job = get_job(config_file, args.name)
  File "/content/ai-toolkit/toolkit/job.py", line 14, in get_job
    from jobs import TrainJob
  File "/content/ai-toolkit/jobs/__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "/content/ai-toolkit/jobs/BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "/content/ai-toolkit/jobs/process/__init__.py", line 1, in <module>
    from .BaseExtractProcess import BaseExtractProcess
  File "/content/ai-toolkit/jobs/process/BaseExtractProcess.py", line 7, in <module>
    from toolkit.metadata import get_meta_for_safetensors
  File "/content/ai-toolkit/toolkit/metadata.py", line 9, in <module>
    from toolkit.train_tools import addnet_hash_legacy
  File "/content/ai-toolkit/toolkit/train_tools.py", line 26, in <module>
    from library.lpw_stable_diffusion import StableDiffusionLongPromptWeightingPipeline
ModuleNotFoundError: No module named 'library'
```

**Comment by jaretburkett** [comment]
Thank you for the kind words and work on colab. This should be solved with this https://github.com/ostris/ai-toolkit/commit/64fbd4c92aa8c2c64059938b5f352b781cf09d41 Let me know if you still have issues.
