### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by Datou** [ostris/ai-toolkit#52]
Could you help me to fix this?

(venv) C:\ai-toolkit>python run.py config/train_lora_flux_24gb.yaml
Running 1 job
C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
C:\ai-toolkit\venv\Lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
{
    "type": "sd_trainer",
    "training_folder": "output/Yoji_Shinkawa",
    "performance_log_every": 1000,
    "device": "cuda:0",
    "trigger_word": "Yoji_Shinkawa",
    "network": {
        "type": "lora",
        "linear": 16,
        "linear_alpha": 16
    },
    "save": {
        "dtype": "float16",
        "save_every": 250,
        "max_step_saves_to_keep": 4
    },
    "datasets": {
        "folder_path": "C:/Yoji_Shinkawa",
        "caption_ext": "txt",
        "caption_dropout_rate": 0.05,
        "shuffle_tokens": false,
        "cache_latents_to_disk": true,
        "resolution": [
            512,
            768,
            1024,
            2048
        ]
    },
    "train": {
        "batch_size": 1,
        "steps": 4000,
        "gradient_accumulation_steps": 1,
        "train_unet": true,
        "train_text_encoder": false,
        "content_or_style": "balanced",
        "gradient_checkpointing": true,
        "noise_scheduler": "flowmatch",
        "optimizer": "adamw8bit",
        "lr": 0.0004,
        "skip_first_sample": true,
        "ema_config": {
            "use_ema": true,
            "ema_decay": 0.99
        },
        "dtype": "bf16"
    },
    "model": {
        "name_or_path": "black-forest-labs/FLUX.1-dev",
        "is_flux": true,
        "quantize": true
    },
    "sample": {
        "sampler": "flowmatch",
        "sample_every": 250,
        "width": 1024,
        "height": 1024,
        "prompts": [
            "a woman holding a coffee cup, in a beanie, sitting at a cafe, [trigger]",
            "a man showing off his cool new t shirt at the beach, a shark is jumping out of the water in the background, [trigger]",
            "a bear building a log cabin in the snow covered mountains, [trigger]",
            "photo of a man, white background, medium shot, modeling clothing, studio lighting, white backdrop, [trigger]",
            "a man holding a sign that says, 'this is a sign', [trigger]",
            "a bulldog, in a post apocalyptic world, with a shotgun, in a leather jacket, in a desert, with a motorcycle"
        ],
        "neg": "",
        "seed": 42,
        "walk_seed": true,
        "guidance_scale": 4,
        "sample_steps": 20
    }
}
Using EMA
Error running job: 'str' object has no attribute 'get'

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\ai-toolkit\run.py", line 77, in main
    job = get_job(config_file, args.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\toolkit\job.py", line 29, in get_job
    return ExtensionJob(config)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\jobs\ExtensionJob.py", line 13, in __init__
    self.load_processes(self.process_dict)
  File "C:\ai-toolkit\jobs\BaseJob.py", line 65, in load_processes
    self.process.append(ProcessClass(i, self, process))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\extensions_built_in\sd_trainer\SDTrainer.py", line 50, in __init__
    super().__init__(process_id, job, config, **kwargs)
  File "C:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 118, in __init__
    raw_datasets = preprocess_dataset_raw_config(raw_datasets)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai-toolkit\toolkit\config_modules.py", line 603, in preprocess_dataset_raw_config
    resolution = dataset.get('resolution', 512)
                 ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

**Comment by Datou** [comment]
I missed a "-"
- folder_path: "C:/Yoji_Shinkawa"

**Comment by Datou** [comment]
it's running now :)
