### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by fbradcdsc** [ostris/ai-toolkit#65]
Trying` to train Flux loras
It happens every time as it's creating buckets

```
Traceback (most recent call last):
  File "C:\Users\andre\Desktop\ai toolkit lora flux\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\Users\andre\Desktop\ai toolkit lora flux\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\Users\andre\Desktop\ai toolkit lora flux\ai-toolkit\run.py", line 78, in main
    job.run()
  File "C:\Users\andre\Desktop\ai toolkit lora flux\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "C:\Users\andre\Desktop\ai toolkit lora flux\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1582, in run
    self.sample(self.step_num)
  File "C:\Users\andre\Desktop\ai toolkit lora flux\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 208, in sample
    for i in range(len(sample_config.prompts)):
TypeError: object of type 'NoneType' has no len()
```

**Comment by fbradcdsc** [comment]
No idea what happened but I messed around with the yaml and it solved itself, can't point out to what exactly fixed it because I changed a bunch of options
