### ISSUE TITLE
ModuleNotFoundError: No module named 'ipadapter.ip_adapter'

### ISSUE THREAD

**Issue by NBSTpeterhill** [ostris/ai-toolkit#66]
Error running job: No module named 'ipadapter.ip_adapter'

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "/root/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/root/ai-toolkit/run.py", line 86, in main
    raise e
  File "/root/ai-toolkit/run.py", line 77, in main
    job = get_job(config_file, args.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ai-toolkit/toolkit/job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "/root/ai-toolkit/jobs/__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "/root/ai-toolkit/jobs/BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "/root/ai-toolkit/jobs/process/__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "/root/ai-toolkit/jobs/process/TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "/root/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 23, in <module>
    from toolkit.custom_adapter import CustomAdapter
  File "/root/ai-toolkit/toolkit/custom_adapter.py", line 11, in <module>
    from toolkit.models.ilora import InstantLoRAModule
  File "/root/ai-toolkit/toolkit/models/ilora.py", line 12, in <module>
    from ipadapter.ip_adapter.resampler import  Resampler
ModuleNotFoundError: No module named 'ipadapter.ip_adapter'

**Comment by fbradcdsc** [comment]
Did you do `git submodule update --init --recursive`?

**Comment by NBSTpeterhill** [comment]
> Did you run `git submodule update --init --recursive`?

yes, I did.

**Comment by fbradcdsc** [comment]
Can you share what fixed it for future reference?

**Comment by olabs-ai** [comment]
This worked for me
git submodule update --init --recursive
