### ISSUE TITLE
Error running job: No module named 'ipadapter.ip_adapter'

### ISSUE THREAD

**Issue by yogotatara3** [ostris/ai-toolkit#68]
Can`t install the 'ipadapter.ip_adapter' to run the yaml file
Do u know a work around and could help me pls?

Best,
Milan

Ps: here is my console print:

(venv) C:\Users\RAIIN Studios\Documents\training\ai-toolkit>python run.py config/train.audis6lora.yaml
Running 1 job
Error running job: No module named 'ipadapter.ip_adapter'

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\run.py", line 77, in main
    job = get_job(config_file, args.name)
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\toolkit\job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\jobs\process\__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\jobs\process\TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 23, in <module>
    from toolkit.custom_adapter import CustomAdapter
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\toolkit\custom_adapter.py", line 11, in <module>
    from toolkit.models.ilora import InstantLoRAModule
  File "C:\Users\RAIIN Studios\Documents\training\ai-toolkit\toolkit\models\ilora.py", line 12, in <module>
    from ipadapter.ip_adapter.resampler import  Resampler
ModuleNotFoundError: No module named 'ipadapter.ip_adapter'

(venv) C:\Users\RAIIN Studios\Documents\training\ai-toolkit>pip install ipadapter.ip_adapter'
ERROR: Invalid requirement: "ipadapter.ip_adapter'"

[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by martintomov** [comment]
You maybe missed to run `git submodule update --init --recursive`.

**Comment by yogotatara3** [comment]
did that in rthe first place. didnt work out. Then installed the whole repo again and for some reason it worked then :)

**Comment by yogotatara3** [comment]
thanks for helping
