### ISSUE TITLE
Error: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hooks'

### ISSUE THREAD

**Issue by martintomov** [ostris/ai-toolkit#76]
## Not my first time using the trainer, but I never got this error before:

Error running job: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hooks'

```
========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\...\flux-train\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\...\flux-train\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\...\flux-train\ai-toolkit\run.py", line 78, in main
    job.run()
  File "C:\...\flux-train\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "C:\...\flux-train\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1230, in run
    self.sd.load_model()
  File "C:\...\flux-train\ai-toolkit\toolkit\stable_diffusion_model.py", line 484, in load_model
    transformer = FluxTransformer2DModel.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\flux-train\env\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\...\flux-train\env\Lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hooks'
(C:\flux-train\env) PS C:\...\flux-train\ai-toolkit>
```

**Comment by martintomov** [comment]
## Fixed it:
```pip install --upgrade accelerate transformers diffusers huggingface_hub```

huggingface_hub must be added to requirements.txt, opening a PR
