### ISSUE TITLE
fbgemm.dll error

### ISSUE THREAD

**Issue by daizhuo** [ostris/ai-toolkit#91]
(venv) C:\Users\daizh\Documents\LORA Traning\ai-toolkit>python run.py config/train_lora_flux_24gb.yaml
Running 1 job
Error running job: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\venv\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\run.py", line 77, in main
    job = get_job(config_file, args.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\toolkit\job.py", line 28, in get_job
    from jobs import ExtensionJob
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\jobs\__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\jobs\BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\jobs\process\__init__.py", line 1, in <module>
    from .BaseExtractProcess import BaseExtractProcess
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\jobs\process\BaseExtractProcess.py", line 4, in <module>
    from safetensors.torch import save_file
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\venv\Lib\site-packages\safetensors\torch.py", line 6, in <module>
    import torch
  File "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\venv\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\daizh\Documents\LORA Traning\ai-toolkit\venv\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

(venv) C:\Users\daizh\Documents\LORA Traning\ai-toolkit>

**Comment by Fikxzer** [comment]
I had this issue found a few answers by googling  "error loading torch\lib\fbgemm.dll"

What worked for me was a link to a file on on dllme.com I was skeptical at first but it worked flawlessly

download libomp140.x86_64.dll from dllme.com and place the file in c:\windows\system32

good luck

I had fixed the same error on another torch install by reinstalling some visual c++ versions I think this file is a shortcut to that fix.

**Comment by greenyellowmill** [comment]
If dll method doesn't seem super safe, you can just install visual studio and get the C++ build tools and the issue will be fixed

**Comment by daizhuo** [comment]
Thank you guys!
After install C++ build tools, all things go smoothly.
