### ISSUE TITLE
Error running job: PEFT backend is required for this method.

### ISSUE THREAD

**Issue by Blutusz** [ostris/ai-toolkit#92]
Lora training FLUX.schnell, getting this error:

```
Running  1 process
Loading Flux model
Loading transformer
Fusing in LoRA
Error running job: PEFT backend is required for this method.

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "C:\data\AI-Toolkit_Trainer\ai-toolkit\run.py", line 90, in <module>
    main()
  File "C:\data\AI-Toolkit_Trainer\ai-toolkit\run.py", line 86, in main
    raise e
  File "C:\data\AI-Toolkit_Trainer\ai-toolkit\run.py", line 78, in main
    job.run()
  File "C:\data\AI-Toolkit_Trainer\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "C:\data\AI-Toolkit_Trainer\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1230, in run
    self.sd.load_model()
  File "C:\data\AI-Toolkit_Trainer\ai-toolkit\toolkit\stable_diffusion_model.py", line 540, in load_model
    pipe.load_lora_weights(self.model_config.lora_path, adapter_name="lora1")
  File "C:\data\AI-Toolkit_Trainer\ai-toolkit\venv\lib\site-packages\diffusers\loaders\lora_pipeline.py", line 1607, in load_lora_weights
    raise ValueError("PEFT backend is required for this method.")
ValueError: PEFT backend is required for this method.

(venv) (base) C:\data\AI-Toolkit_Trainer\ai-toolkit> 
```

I remembered about this:

`        assistant_lora_path: "ostris/FLUX.1-schnell-training-adapter"`

This may come handy:

```
Package                   Version
------------------------- ------------
absl-py                   2.1.0
accelerate                0.33.0
albucore                  0.0.13
albumentations            1.4.14
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
attrs                     24.2.0
bitsandbytes              0.43.3
certifi                   2024.7.4
charset-normalizer        3.3.2
clean-fid                 0.1.35
click                     8.1.7
clip-anytorch             2.6.0
colorama                  0.4.6
controlnet-aux            0.0.7
dctorch                   0.1.2
diffusers                 0.31.0.dev0
docker-pycreds            0.4.0
einops                    0.8.0
eval_type_backport        0.2.0
filelock                  3.13.1
flatten-json              0.1.14
fsspec                    2024.2.0
ftfy                      6.2.3
gitdb                     4.0.11
GitPython                 3.1.43
grpcio                    1.65.5
hf_transfer               0.1.8
huggingface-hub           0.24.5
idna                      3.7
imageio                   2.35.0
importlib_metadata        8.2.0
invisible-watermark       0.2.0
Jinja2                    3.1.3
jsonmerge                 1.9.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
k-diffusion               0.1.1.post1
kornia                    0.7.3
kornia_rs                 0.1.5
lazy_loader               0.4
lpips                     0.1.4
lycoris-lora              1.8.3
Markdown                  3.7
MarkupSafe                2.1.5
mpmath                    1.3.0
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.3
omegaconf                 2.3.0
open_clip_torch           2.26.1
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
optimum-quanto            0.2.4
oyaml                     1.0
packaging                 24.1
pillow                    10.2.0
pip                       23.0.1
platformdirs              4.2.2
prodigyopt                1.0
protobuf                  5.27.3
psutil                    6.0.0
pydantic                  2.8.2
pydantic_core             2.20.1
python-dotenv             1.0.1
pytorch-fid               0.3.0
PyWavelets                1.7.0
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
rpds-py                   0.20.0
safetensors               0.4.4
scikit-image              0.24.0
scipy                     1.14.0
sentencepiece             0.2.0
sentry-sdk                2.13.0
setproctitle              1.3.3
setuptools                65.5.0
six                       1.16.0
smmap                     5.0.1
sympy                     1.12
tensorboard               2.17.1
tensorboard-data-server   0.7.2
tifffile                  2024.8.10
timm                      1.0.8
tokenizers                0.19.1
toml                      0.10.2
tomli                     2.0.1
torch                     2.4.0+cu121
torchdiffeq               0.2.4
torchsde                  0.2.6
torchvision               0.19.0+cu121
tqdm                      4.66.5
trampoline                0.1.2
transformers              4.44.0
typing_extensions         4.9.0
urllib3                   2.2.2
wandb                     0.17.7
wcwidth                   0.2.13
Werkzeug                  3.0.3
zipp                      3.20.0
```

**Comment by harmonicoclamor** [comment]
install peft B)

`pip install peft`

**Comment by Blutusz** [comment]
> install peft B)
> 
> `pip install peft`

Damn, I need a brake :D It worked, case closed.
