### ISSUE TITLE
lora train on schnell

### ISSUE THREAD

**Issue by pjrpjr** [ostris/ai-toolkit#97]
Running  1 process
Loading Flux model
Loading transformer
Grabbing assistant lora from the hub: ostris/FLUX.1-schnell-training-adapter
Fusing in LoRA
Error running job: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "/home/tom/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/home/tom/ai-toolkit/run.py", line 86, in main
    raise e
  File "/home/tom/ai-toolkit/run.py", line 78, in main
    job.run()
  File "/home/tom/ai-toolkit/jobs/ExtensionJob.py", line 22, in run
    process.run()
  File "/home/tom/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 1230, in run
    self.sd.load_model()
  File "/home/tom/ai-toolkit/toolkit/stable_diffusion_model.py", line 541, in load_model
    pipe.fuse_lora()
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/diffusers/loaders/lora_pipeline.py", line 1932, in fuse_lora
    super().fuse_lora(
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/diffusers/loaders/lora_base.py", line 451, in fuse_lora
    model.fuse_lora(lora_scale, safe_fusing=safe_fusing, adapter_names=adapter_names)
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/diffusers/loaders/peft.py", line 270, in fuse_lora
    self.apply(partial(self._fuse_lora_apply, adapter_names=adapter_names))
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 895, in apply
    module.apply(fn)
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 895, in apply
    module.apply(fn)
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 895, in apply
    module.apply(fn)
  [Previous line repeated 1 more time]
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 896, in apply
    fn(self)
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/diffusers/loaders/peft.py", line 292, in _fuse_lora_apply
    module.merge(**merge_kwargs)
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 453, in merge
    delta_weight = self.get_delta_weight(active_adapter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/ai-toolkit/venv/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 520, in get_delta_weight
    output_tensor = transpose(weight_B @ weight_A, self.fan_in_fan_out) * self.scaling[adapter]
                              ~~~~~~~~~^~~~~~~~~~
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)

**Comment by jaretburkett** [comment]
This is basically an OOM error. Please verify that you have at least 24GB of VRAM and that you are using the example config. If you are still having issues. Please ask [in the discord](https://discord.com/invite/nuR9zZ2nsh).
