### ISSUE TITLE
Have a bug when training the lora slider? No folder networks in repo.

### ISSUE THREAD

**Issue by ngsitrong26** [ostris/ai-toolkit#99]
Traceback (most recent call last):
  File "/workspace/ai-toolkit/run.py", line 90, in <module>
    main()
  File "/workspace/ai-toolkit/run.py", line 86, in main
    raise e
  File "/workspace/ai-toolkit/run.py", line 77, in main
    job = get_job(config_file, args.name)
  File "/workspace/ai-toolkit/toolkit/job.py", line 19, in get_job
    from jobs import TrainJob
  File "/workspace/ai-toolkit/jobs/__init__.py", line 1, in <module>
    from .BaseJob import BaseJob
  File "/workspace/ai-toolkit/jobs/BaseJob.py", line 5, in <module>
    from jobs.process import BaseProcess
  File "/workspace/ai-toolkit/jobs/process/__init__.py", line 8, in <module>
    from .TrainSliderProcess import TrainSliderProcess
  File "/workspace/ai-toolkit/jobs/process/TrainSliderProcess.py", line 26, in <module>
    from .BaseSDTrainProcess import BaseSDTrainProcess
  File "/workspace/ai-toolkit/jobs/process/BaseSDTrainProcess.py", line 30, in <module>
    from toolkit.lora_special import LoRASpecialNetwork
  File "/workspace/ai-toolkit/toolkit/lora_special.py", line 20, in <module>
    from networks.lora import LoRANetwork, get_block_index
ModuleNotFoundError: No module named 'networks'

**Comment by jaretburkett** [comment]
This usually happens when the `git submodule update --init --recursive` was not executed of the command failed. Please try that again.
